---
title: "DO_Phenotypes"
author: "Adam Kirosingh"
date: "October 11, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

setwd("~/GitHub/Diversity-Outbred-Malaria-Project/Malaria_Diversity_Outbred_Project/Setup/Creating_Phenotype_File")

library(tidyverse)
library(readr)

Data <- read_csv("axiom8_RawData.csv")

Data$Sex <- "F"
```

# Making an initial weight and temperature dataframe
```{r}
#This converts columns we care about to numeric
id <- c("Temperature","Weight", "Accuri Count")
Data[id] = data.matrix(Data[id])

Day0 <- Data[Data$Day==0,]

Initial <- subset(Day0, select = c("Number", "Temperature", "Weight"))
names(Initial) <- c("Number", "Initial Temperature", "Initial Weight")
Datai <-  merge(Data,Initial)


```

# Computing Mouse physiology parameters
```{r}

Dataic <- Datai %>%
  # calculate percent weight relative to day 0
  mutate(`Percent Bodyweight` = ((Datai$Weight) / (Datai$`Initial Weight`) * 100))  %>%
  # calculate percent weight loss relative to day 0
  mutate(`Percent Change in Weight` = (((Datai$Weight)-(Datai$`Initial Weight`)) / (Datai$`Initial Weight`)) * 100)%>%
  # calculate weight loss relative to day 0
  mutate(`Change in Weight` = (Datai$Weight)-(Datai$`Initial Weight`)) %>%
  # calculate RBCs from raw accuri score
  mutate(RBC = (Datai$`Accuri Count`) / 2000) %>%  
  # calculate delta temperature relative to day 0
  mutate(`Change in Temperature` = ((Datai$Temperature) - (Datai$`Initial Temperature`))) %>%
  # calculate parasite density 
  mutate(`Parasite Density` = Parasitemia * RBC)

# Removing a measurement error
Dataic$RBC[2710] <- NA
Dataic %>%
  subset(Number == 210 & Day == 0) %>%
  select(RBC) 
```

# Summarizing Statistics for QTL Analysis

```{r}

Phenotypes <- Dataic %>% 
  subset(Day %in% c(0,5:15)) %>%
  group_by(Number) %>%
  summarize(White = as.numeric(`Coat Color`[Day==0]== "White"),
            Black = as.numeric(`Coat Color`[Day==0]== "Black"),
            Star = `Star?`[Day==0],
            Lived = `Lived?`[Day==0],
            MinDeltaTemp = min(`Change in Temperature`, na.rm = TRUE),
            Day0Weight= `Initial Weight`[Day==0],
            MinPercWeight = min(`Percent Change in Weight`, na.rm=TRUE),
            MinDeltaWeight = min(`Change in Weight`, na.rm = TRUE),
            #This is likely just a measure of age since only young mice are this phenotype
            #Gainer = as.numeric(MinDeltaWeight==0), 
            MinRBC= min(RBC, na.rm=TRUE),
            MaxPD = max(`Parasite Density`, na.rm=TRUE),
            MaxParasitemia = max(Parasitemia, na.rm = TRUE),
            Description = Description[1])

# Changing experimental measurements from a mouse (415) that died before the experiment 
Phenotypes[397,6:13] <- NA

Phenotypes$MinDeltaTemp[Phenotypes$Lived==0] <- NA
```

# Clustering Mice

```{r}
#install.packages("kmlShape")
library("kmlShape")
names(Dataic)
DO_Experimentclean <- Dataic %>%
  select("Number", "Day", "Change in Temperature")

DO_Experimentclean <- as.data.frame(DO_Experimentclean)
ShortDO_Experimentclean <- DO_Experimentclean %>%
  subset(Day %in% 0:15 & is.na(`Change in Temperature`)==FALSE)


ShortDO_Experimentclean <- as.data.frame(ShortDO_Experimentclean)
myClds <- cldsLong(ShortDO_Experimentclean)
### Reducing the data size
#reduceTraj(myClds,nbSenators=64,nbTimes=7)
### Clustering using shape
set.seed(10232019)
kmlShape(myClds,3)

Temperature <- as.data.frame(myClds@clusters)
Temperature$Number <- rownames(Temperature)
names(Temperature)[1] <- "TempClusters"

DO_Experimentclean <- Dataic %>%
  select("Number", "Day", "RBC")

DO_Experimentclean <- as.data.frame(DO_Experimentclean)
ShortDO_Experimentclean <- DO_Experimentclean %>%
  subset(Day %in% 0:15 & is.na(`RBC`)==FALSE)


ShortDO_Experimentclean <- as.data.frame(ShortDO_Experimentclean)
myClds <- cldsLong(ShortDO_Experimentclean)
### Reducing the data size
#reduceTraj(myClds,nbSenators=64,nbTimes=7)
### Clustering using shape
set.seed(10232019)
kmlShape(myClds,3)

RBC <- as.data.frame(myClds@clusters)
RBC$Number <- rownames(RBC)
names(RBC)[1] <- "RBCClusters"

DO_Experimentclean <- Dataic %>%
  select("Number", "Day", "Parasitemia")
names(Dataic)
DO_Experimentclean <- as.data.frame(DO_Experimentclean)
ShortDO_Experimentclean <- DO_Experimentclean %>%
  subset(Day %in% 0:15 & is.na(Parasitemia)==FALSE)


ShortDO_Experimentclean <- as.data.frame(ShortDO_Experimentclean)
myClds <- cldsLong(ShortDO_Experimentclean)
### Reducing the data size
#reduceTraj(myClds,nbSenators=64,nbTimes=7)
### Clustering using shape
set.seed(10232019)
kmlShape(myClds,3)

Parasitemia <- as.data.frame(myClds@clusters)
Parasitemia$Number <- rownames(Parasitemia)
names(Parasitemia)[1] <- "ParasitemiaClusters"

Combined <-merge(Parasitemia,Temperature, by = "Number")

ggplot(Combined, aes(x= ParasitemiaClusters, y = TempClusters)) + geom_jitter()
```

#Normalizing Data

```{r Normalizing Data}
# One of the assumptions of qtl2 is that the data is either binary (0 or 1) or follows a normal distribution. Since a few phenotypes of disease severity do not follow a normal distribution, I will use log transformation to make the distribution more normal.

# Notice how Minimum Change in temperature does not follow a normal distribution
qqnorm(Phenotypes$MinDeltaTemp) 
qqline(Phenotypes$MinDeltaTemp)

# When we do a log transformation after taking the absolute value and adding one we get pretty close
logt <- log(abs(Phenotypes$MinDeltaTemp)+1)
qqnorm(logt) 
qqline(logt)

# Just to compare methods I will also try yeo.johnson function from the VGAM function.
# install.packages("VGAM")
library(VGAM)

yj <-yeo.johnson(na.omit(Phenotypes$MinDeltaTemp), lambda = 2)
qqnorm(yj)
qqline(yj)

# The variance appears to be the same between log transforming the absolute value and adding one and doing the yeo.johnson transformation
var(Phenotypes$MinDeltaTemp,na.rm = T)
var(log(abs(Phenotypes$MinDeltaTemp)+1),na.rm = T)
var(yj,na.rm = T)

# With Minimum RBC distribution also isn't quite normal but is closer with a log transformation
qqnorm(na.omit(Phenotypes$MinRBC))
qqline(na.omit(Phenotypes$MinRBC))

qqnorm(log(na.omit(Phenotypes$MinRBC)))
qqline(log(na.omit(Phenotypes$MinRBC)))

# With Parasite Density and Parasitemia there are a lot of mice that didn't have detectable level of parasites. If we exclude these samples we are also closer to a normal distribution

Detectable <-Phenotypes %>%
  subset(MaxPD !=0)

qqnorm(Phenotypes$MaxPD)
qqline(Phenotypes$MaxPD)

qqnorm(Detectable$MaxPD)
qqline(Detectable$MaxPD)

# Now let's add these transformations to the Phenotypes Dataframe

# First we will take out our NA Mouse (415) and add the transformation then add the mouse back in and arrange by mouse number
NoNADO <-Phenotypes[-397,] %>%
  mutate(logMinDeltaTemp = log(abs(MinDeltaTemp)+1), logMinRBC = log(MinRBC), DetectableMaxPD = ifelse(MaxPD ==0,NA,MaxPD), DetectableParasitemia = ifelse(MaxParasitemia ==0, NA, MaxParasitemia)) 

# Removing Parental strains and mouse 503 because there isn't genotyping information with it 
DO_Phenotypes <- bind_rows(NoNADO,Phenotypes[397,]) %>% filter(Description =="DO" & Number != 503)

# Adding placeholders for Mice c(175,178,187,194,199,203,216,220,228,244,343)
Placeholders <- tibble(Number = c(175,178,187,194,199,203,216,220,228,244,343,415))
Phenotypes_missing <-bind_rows(DO_Phenotypes, Placeholders)  %>% arrange(Number)



axiom8_NumberSamples <- read_csv("axiom8_NumberSamples.csv")


SemiFinal_Phenotypes <-as_tibble(merge(Phenotypes_missing, axiom8_NumberSamples, by = "Number"))
Final_Phenotypes <-merge(SemiFinal_Phenotypes, Combined, by = "Number",all=T)

axiom8_phenotypes <-Final_Phenotypes %>%
  dplyr::select(SampleID, Number, White:TempClusters) %>%
  mutate(TempCluster1 = ifelse(TempClusters==1,1,0),TempCluster2 = ifelse(TempClusters==2,1,0), TempCluster3 = ifelse(TempClusters==3,1,0), ParasitemiaCluster1 = ifelse(ParasitemiaClusters==1,1,0),ParasitemiaCluster2 = ifelse(ParasitemiaClusters==2,1,0), ParasitemiaCluster3 = ifelse(ParasitemiaClusters==3,1,0))

#Removing Hermoine to see if Gainer phenotype is real
#axiom8_phenotypes <-axiom8_phenotypes %>%
#  mutate(HerGainer = ifelse(Number %in% c(1:470),Gainer,NA))
axiom8_phenotypes <-axiom8_phenotypes %>%
  mutate(Died = ifelse(Lived == 0, 1,0))

completeFun <- function(data, desiredCols) {
  completeVec <- complete.cases(data[, desiredCols])
  return(data[completeVec, ])
}

axiom8_phenotypes <-completeFun(axiom8_phenotypes,"SampleID") %>% arrange(SampleID)
str(axiom8_phenotypes)
p <- file("axiom8_phenotypes.csv", "w")
writeLines("#phenotype data for axiom8",p)
writeLines("#ncol 27",p)
writeLines("#nrow 501",p)
write.csv(x = axiom8_phenotypes, file = p,row.names = F)
close(p)

library(readr)
axiom8_phenotypes <- read_csv("axiom8_phenotypes.csv", skip = 3)
library(readr)
axiom7_pheno_20190827 <- read_csv("~/axiom7/axiom7_pheno_20190827.csv", 
    skip = 3)

axiom7_pheno_20190827$Number[!(axiom7_pheno_20190827$Number %in% axiom8_phenotypes$Number)]
```

#Diagnostic Plots

```{r Diagnostic Plots}
theme_set(theme_classic(base_size = 18))
?theme_classic
Phenotypes$Description <- factor(Phenotypes$Description, levels = c("A/J", "C57BL/6J", "129S1/SvImJ", "NOD/ShiLtJ", "NZO/HILtJ", "CAST/EiJ", "PWK/PhJ", "WSB/EiJ","DO"))

strain_colors <- c("#FFDC00", "DarkGrey", "LightPink", "#0064C9", "#7FDBFF", "#2ECC40", "#FF4136", "#B10DC9", "LightGrey") 


ggplot(Phenotypes, aes(x = White, y = Black, color = Description)) + geom_jitter() + scale_color_manual(values = strain_colors )

ggplot(Phenotypes, aes(x = Star, y = Lived, color = Description)) + geom_jitter() + scale_color_manual(values = strain_colors )

ggplot(Phenotypes, aes(x = MinDeltaWeight, y = Lived, color = Description)) + geom_jitter() + scale_color_manual(values = strain_colors )

ggplot(Phenotypes, aes(x = MinPercWeight, y = MinRBC, color = Description)) + geom_point() + scale_color_manual(values = strain_colors )



```


```{r}
library(readr)
axiom8_phenotypes <- read_csv("axiom7/axiom8_phenotypes.csv", skip = 3)
head(axiom8_phenotypes)
axiom8_Par <- axiom8_phenotypes %>% select(Number,ParasitemiaClusters) 
Together <-merge(Dataic, axiom8_Par, by = "Number")
InterestTogether <- subset(Together,is.na(Together$ParasitemiaClusters)==F)
InterestTogether$ParasitemiaClusters <- as.factor(InterestTogether$ParasitemiaClusters)
levels(InterestTogether$ParasitemiaClusters) <- c("Moderate", "Mild", "Severe")
InterestTogether$ParasitemiaClusters <-factor(InterestTogether$ParasitemiaClusters, levels = c("Mild", "Moderate", "Severe"))
ggplot(InterestTogether, aes(x = Day, y = Parasitemia, color = ParasitemiaClusters, group = Number)) + scale_x_continuous(limits=c(0,15), expand = c(0,0))+ scale_y_continuous(expand = c(0,0))+ theme_classic(base_size = 17) + geom_line(size = 1, alpha =0.7) + facet_wrap(~ParasitemiaClusters) + theme(legend.position = "none") + scale_color_manual(values = c("#9dab86","#fbe3b9","#e08f62"))

levels(InterestTogether$ParasitemiaClusters)
head(Dataic)
```


# Replicating Victoria's Figure

```{r}
#install.packages("plotrix")
library(plotrix)
# 
head(Dataic)
ggplot(Dataic, aes( x= Day, y = RBC, group = Number, color = Description))+ geom_line() + xlim(c(0,15))
head(Dataic)
Grouped <- Dataic %>%
  subset(Description != "DO") %>%
  group_by(Description, Day) %>%
  summarize(RBCavg = mean(RBC,na.rm = T), RBCse = std.error(RBC, na.rm = T), Parasitemiaavg = mean(Parasitemia, na.rm = T), Parasitemiase = std.error(Parasitemia, na.rm = T), PercentChangeinWeightavg = mean(`Percent Change in Weight`,na.rm=T), PercentChangeinWeightse = std.error(`Percent Change in Weight`,na.rm = T), ChangeinTemperatureavg = mean(`Change in Temperature`, na.rm=T), ChangeinTemperaturese = std.error(`Change in Temperature`, na.rm=T), ParasiteDensityavg = mean(`Parasite Density`, na.rm=T), ParasiteDensityse = std.error(`Parasite Density`, na.rm = T) )

Grouped$Description <- factor(Grouped$Description, levels = c("A/J", "C57BL/6J", "129S1/SvImJ", "NOD/ShiLtJ", "NZO/HILtJ", "CAST/EiJ", "PWK/PhJ", "WSB/EiJ","DO"))

Dataic$Description <- factor(Dataic$Description, levels = c("A/J", "C57BL/6J", "129S1/SvImJ", "NOD/ShiLtJ", "NZO/HILtJ", "CAST/EiJ", "PWK/PhJ", "WSB/EiJ","DO"))

strain_colors <- c("#FFDC00", "DarkGrey", "LightPink", "#0064C9", "#7FDBFF", "#2ECC40", "#FF4136", "#B10DC9", "LightGrey") 

#RBC
A <- ggplot(Grouped, aes(x = Day, y = RBCavg, color = Description))  + geom_ribbon(aes(ymax = RBCavg + RBCse, ymin = RBCavg- RBCse, fill = Description), color = NA, alpha =0.3) + geom_line( size = 0.8) + scale_color_manual(values = strain_colors) +  scale_fill_manual(values = strain_colors)+ labs(y = expression(atop(paste("10"^"6"," RBC"),"per ??L of Blood")), x = "")+ theme(legend.position = "none", axis.title.y = element_text(size = 12)) + scale_x_continuous(limits = c(0,15), expand = c(0,0)) +scale_y_continuous(limits = c(0,11), expand = c(0,0))


B <- ggplot(Grouped, aes(x = Day, y = RBCavg, color = Description)) + geom_line(data = subset(Dataic,Dataic$Description=="DO"),aes(x=Day,y=RBC, group = Number), color = "Light gray", alpha = 0.5) + geom_line( size = 0.8)+ scale_color_manual(values = strain_colors)  + labs(y = expression(atop(paste("10"^"6"," RBC"),"per ??L of Blood")), x = "")+ theme(legend.position = "none", axis.title.y = element_text(size = 12)) + scale_x_continuous(limits = c(0,15), expand = c(0,0)) +scale_y_continuous(limits = c(0,11), expand = c(0,0))


#PercentChangeinWeight
C <- ggplot(Grouped, aes(x = Day, y = PercentChangeinWeightavg, color = Description))  + geom_ribbon(aes(ymax = PercentChangeinWeightavg + PercentChangeinWeightse, ymin = PercentChangeinWeightavg- PercentChangeinWeightse, fill = Description), color = NA, alpha =0.3) + geom_line( size = 0.8) + scale_color_manual(values = strain_colors) +  scale_fill_manual(values = strain_colors) + labs(y = "Percent Change in Weight", x = "")+ theme(legend.position = "none", axis.title.y = element_text(size = 12))+ scale_x_continuous(limits = c(0,15), expand = c(0,0)) +scale_y_continuous(limits = c(-30,35), expand = c(0,0))

D <- ggplot(Grouped, aes(x = Day, y = PercentChangeinWeightavg, color = Description))  + geom_line(data = subset(Dataic,Dataic$Description=="DO"),aes(x=Day,y=`Percent Change in Weight`, group = Number),color = "Light gray", alpha = 0.5) + geom_line( size = 0.8)+ scale_color_manual(values = strain_colors)  + labs(y = "Percent Change in Weight", x = "")+ theme(legend.position = "none", axis.title.y = element_text(size = 12)) + scale_x_continuous(limits = c(0,15), expand = c(0,0)) +scale_y_continuous(limits = c(-30,35), expand = c(0,0))



#Change in Temperature
E <-  ggplot(Grouped, aes(x = Day, y = ChangeinTemperatureavg, color = Description))  + geom_ribbon(aes(ymax = ChangeinTemperatureavg + ChangeinTemperaturese, ymin = ChangeinTemperatureavg- ChangeinTemperaturese, fill = Description), color = NA, alpha =0.3) + geom_line( size = 0.8) + scale_color_manual(values = strain_colors) +  scale_fill_manual(values = strain_colors) + labs(y = "Change in Temperature (°C)", x = "")+theme(legend.position = "none", axis.title.y = element_text(size = 12)) + scale_x_continuous(limits = c(0,15), expand = c(0,0)) +scale_y_continuous(limits = c(-16,4), expand = c(0,0))

F <- ggplot(Grouped, aes(x = Day, y = ChangeinTemperatureavg, color = Description))  + geom_line(data = subset(Dataic,Dataic$Description=="DO"),aes(x=Day,y=`Change in Temperature`, group = Number),color = "Light gray", alpha = 0.5) + geom_line( size = 0.8)+ scale_color_manual(values = strain_colors)   + labs(y = "Change in Temperature (°C)", x = "")+ theme(legend.position = "none", axis.title.y = element_text(size = 12)) + scale_x_continuous(limits = c(0,15), expand = c(0,0)) +scale_y_continuous(limits = c(-16,4), expand = c(0,0))


#Parasitemia
G <- ggplot(Grouped, aes(x = Day, y = Parasitemiaavg, color = Description))  + geom_ribbon(aes(ymax = Parasitemiaavg + Parasitemiase, ymin = Parasitemiaavg- Parasitemiase, fill = Description), color = NA, alpha =0.3) + geom_line( size = 0.8) + scale_color_manual(values = strain_colors) +  scale_fill_manual(values = expression(atop("Parasitemia",paste("(Infected RBC per Total RBC)"))), x = "") + theme(legend.position = "none", axis.title.y = element_text(size = 12))  + scale_x_continuous(limits = c(0,15), expand = c(0,0)) +scale_y_continuous(limits = c(0,0.6), expand = c(0,0))

H <- ggplot(Grouped, aes(x = Day, y = Parasitemiaavg, color = Description)) + geom_line(data = subset(Dataic,Dataic$Description=="DO"),aes(x=Day,y=Parasitemia, group = Number), color = "Light gray", alpha = 0.5) + geom_line( size = 0.8)+ scale_color_manual(values = strain_colors)  + labs(y = expression(atop("Parasitemia",paste("(Infected RBC per Total RBC)"))), x = "")+ theme(legend.position = "none", axis.title.y = element_text(size = 12)) + scale_x_continuous(limits = c(0,15), expand = c(0,0)) +scale_y_continuous(limits = c(0,0.6), expand = c(0,0))


#Parasite Density 
I <- ggplot(Grouped, aes(x = Day, y = ParasiteDensityavg, color = Description)) + geom_ribbon(aes(ymax = ParasiteDensityavg + ParasiteDensityse, ymin = ParasiteDensityavg- ParasiteDensityse, fill = Description), color = NA, alpha =0.3) + geom_line( size = 0.8) + scale_color_manual(values = strain_colors) +  scale_fill_manual(values = strain_colors) + labs(y = expression(atop("Parasite Density",paste("(10"^"6"," Parasites per ??L of Blood)"))), x = "Day Post Infection")  + theme(legend.position = "none", axis.title.y = element_text(size = 12)) + scale_x_continuous(limits = c(0,15), expand = c(0,0)) +scale_y_continuous(limits = c(0,2.5), expand = c(0,0))


J <- ggplot(Grouped, aes(x = Day, y = ParasiteDensityavg, color = Description)) + geom_line(data = subset(Dataic,Dataic$Description=="DO"),aes(x=Day,y=`Parasite Density`, group = Number), color = "Light gray", alpha = 0.5) + geom_line( size = 0.8)+ scale_color_manual(values = strain_colors, name = "Mouse Strain")  + labs(y = expression(atop("Parasite Density",paste("(10"^"6"," Parasites per ??L of Blood)"))), x = "Day Post Infection")+ scale_x_continuous(limits = c(0,15), expand = c(0,0)) +scale_y_continuous(limits = c(0,2.5), expand = c(0,0))+ theme(axis.title.y = element_text(size = 12), legend.position = "none") 




unique(Grouped$Description)

library(ggpubr)

p <- ggarrange(A,B,C,D,E,F,G,H,I,J, labels = c("A","B","C","D","E","F","G","H","I","J"), nrow = 5, ncol = 2, align = "v")

?ggsave
install.packages("svglite")
library(svglite)
ggsave("Figure2", device = "pdf", plot = p, height = 14, width = 12,units = "in" )

plegend <- ggplot(Dataic, aes(x = Day, y = RBC, group = Number , color = Description)) + geom_line(size = 5) + scale_color_manual(values = strain_colors, name = "Mouse Strains") + theme(legend.position = "bottom")

ggsave("Figure2Legend", device = "pdf", plot = plegend, height = 14, width = 12,units = "in")

Dataic %>%
  subset(Day==0) %>%
  select(Description) %>%
  table()

```



