---
title: "Clustering"
author: "Adam Kirosingh"
date: "2/5/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(beepr)
library(readxl)

DO_Experiment <- read_csv("axiom8_RawData.csv")

NoDO <- subset(DO_Experiment,DO_Experiment$Description != "DO")

# I want days 5 and 7 malaria percentages

interest <- subset(NoDO, NoDO$Day %in% c(5,7))

write.table(interest)
write_csv(interest, "Microscopy.csv")


test <- DO_Experiment %>%
  subset(Batch == "Bellatrix")

table(test$Day)


unique(DO_Experiment$Batch)

Clusters <- read_excel(path = "../Documents/Temperature and Percent Weightloss Clusters.xlsx")

Clusters$MouseID <- sub('.', '', Clusters$MouseID)

Mofinterest <- subset(Clusters, Clusters$MouseID %in% unique(DO_Experiment$Number))

Clusters$MouseID %in% unique(DO_Experiment$Number)
length(Mofinterest$MouseID)
library("kmlShape")
```


```{r}
#########
### Real example, on ictus data
### Preparing the data



DO_Experimentclean <- DO_Experiment %>%
  select("Number", "Day", "Percent Weight Loss")


DO_Experimentclean[is.na(DO_Experimentclean)] 
DO_Experimentclean <- as.data.frame(DO_Experimentclean)
ShortDO_Experimentclean <- DO_Experimentclean %>%
  subset(Day %in% 0:15 & is.na(`Percent Weight Loss`)==FALSE)

sum(is.na(ShortDO_Experimentclean$`Percent Weight Loss`))
ShortDO_Experimentclean <- as.data.frame(ShortDO_Experimentclean)
myClds <- cldsLong(ShortDO_Experimentclean)
### Reducing the data size
#reduceTraj(myClds,nbSenators=64,nbTimes=7)
### Clustering using shape
kmlShape(myClds,3)

Weight <- as.data.frame(myClds@clusters)
Weight$`Mouse ID` <- rownames(Weight)

Combined <- merge(ShortDO_Experimentclean, Weight, by = "Mouse ID")

ggplot(Combined, aes(x = Day, y = `Percent Weight Loss`, group = `Mouse ID`)) + geom_line(aes(color = `myClds@clusters`), alpha=0.8, size = 1.1 )+ theme_classic(base_size = 18) + labs(y = "Percent Weight Loss") + scale_color_manual(name = "Clusters",values = c("#ffe5c8","#a5c5c5",  "#fbc1bb")) + theme(legend.position = c(0.2,0.2))
write.csv(as.data.frame(myClds@clusters), "PercentWeightlossclusters.csv")
DO_Experimentclean <- DO_Experiment %>%
  select("Mouse ID", "Day", "Delta Temperature") 

ggplot(DO_Experimentclean, aes(x= Day, y = `Delta Temperature`, color = `Mouse ID`)) +geom_point() +theme(legend.position = "none")

DO_Experimentclean <- as.data.frame(DO_Experimentclean)

ShortDO_Experimentclean <- DO_Experimentclean %>%
  subset(Day %in% 0:15 & is.na(`Delta Temperature`)==FALSE)
ShortDO_Experimentclean <- as.data.frame(ShortDO_Experimentclean)

myClds <- cldsLong(ShortDO_Experimentclean)
### Reducing the data size
### Clustering using shape
kmlShape(myClds,3)

Tempclusters <- as.data.frame(myClds@clusters)
Tempclusters$`Mouse ID` <- rownames(Tempclusters)

Combined <- merge(ShortDO_Experimentclean, Tempclusters, by = "Mouse ID")

ggplot(Combined, aes(x = Day, y = `Delta Temperature`, group = `Mouse ID`)) + geom_line(aes(color = `myClds@clusters`), alpha=0.8, size = 1.1 )+ theme_classic(base_size = 18) +theme(legend.position = "none") + labs(y = "Change in Temperature (˚C)") + scale_color_manual(name = "Clusters",values = c("#ffe5c8","#a5c5c5",  "#fbc1bb")) + theme(legend.position = c(0.2,0.2))

write.csv(as.data.frame(myClds@clusters), "DeltaTemperature.csv")

DO_Experimentclean <- DO_Experiment %>%
  select("Mouse ID", "Day", "Parasite Density (based on Parasitemia)") 

ggplot(DO_Experimentclean, aes(x= Day, y = `Parasite Density (based on Parasitemia)`, color = `Mouse ID`)) +geom_point() +theme(legend.position = "none")

DO_Experimentclean <- as.data.frame(DO_Experimentclean)

ShortDO_Experimentclean <- DO_Experimentclean %>%
  subset(Day %in% 0:15 & is.na(`Parasite Density (based on Parasitemia)`)==FALSE)
ShortDO_Experimentclean <- as.data.frame(ShortDO_Experimentclean)

myClds <- cldsLong(ShortDO_Experimentclean)
### Reducing the data size
### Clustering using shape
set.seed(2019)
kmlShape(myClds,3)
clusters <- as.data.frame(myClds@clusters)
Moreclusters <- clusters %>%
  mutate(mouse = rownames(clusters)) %>%
  mutate(PDensity1 = ifelse(myClds@clusters==1,1,0)) %>%
  mutate(PDensity2 = ifelse(myClds@clusters==2,1,0)) %>%
  mutate(PDensity3 = ifelse(myClds@clusters==3,1,0))
write.csv(Moreclusters, "Parasite Density.csv")

plotMeans(myClds)

DO_Experimentclean <- DO_Experiment %>%
  select("Mouse ID", "Day", "RBC (million/uL)")


ShortDO_Experimentclean <- DO_Experimentclean %>%
  subset(Day %in% 0:15 & is.na(`RBC (million/uL)`)==FALSE)
ShortDO_Experimentclean <- as.data.frame(ShortDO_Experimentclean)

myClds <- cldsLong(ShortDO_Experimentclean)
### Reducing the data size
### Clustering using shape
kmlShape(myClds,3)
plotMeans(myClds)

DO_Experimentclean <- DO_Experiment %>%
  select("Mouse ID", "Day", "RBC (million/uL)") 

ggplot(DO_Experimentclean, aes(x= Day, y = `RBC (million/uL)`, color = `Mouse ID`)) +geom_point() +theme(legend.position = "none")

DO_Experimentclean <- as.data.frame(DO_Experimentclean)

ShortDO_Experimentclean <- DO_Experimentclean %>%
  subset(Day %in% 0:15 & is.na(`RBC (million/uL)`)==FALSE)
ShortDO_Experimentclean <- as.data.frame(ShortDO_Experimentclean)

myClds <- cldsLong(ShortDO_Experimentclean)
### Reducing the data size
### Clustering using shape
set.seed(2019)
kmlShape(myClds,3)
clusters <- as.data.frame(myClds@clusters)
Moreclusters <- clusters %>%
  mutate(mouse = rownames(clusters)) %>%
  mutate(RBC1 = ifelse(myClds@clusters==1,1,0)) %>%
  mutate(RBC2 = ifelse(myClds@clusters==2,1,0)) %>%
  mutate(RBC3 = ifelse(myClds@clusters==3,1,0))
write.csv(Moreclusters, "RBC.csv")

```


```{r}
library("kml3d")

### 1. Data Preparation
data(pregnandiol)
names(pregnandiol)
cld3dPregTemp <- cld3d(pregnandiol,timeInData=list(temp=1:30*2,preg=1:30*2+1))
pregnandiol
list(temp=1:7.5*2,preg=1:7.5*2+1)
### 2. Building "optimal" clusteration (with only 2 redrawings)
### Real analysis needs at least 20 redrawings
kml3d(cld3dPregTemp,3:5,nbRedrawing=4,toPlot="both")
### 3. Exporting results
try(choice(cld3dPregTemp))
### 4. Visualizing in 3D
plotMeans3d(cld3dPregTemp,4)


DO_Experimentclean <- DO_Experiment %>%
  select("Day", "Mouse ID", "Delta Temperature") %>%
  subset(Day %in% c(0:15))

test <- spread(DO_Experimentclean, key = "Day", value ="Delta Temperature", sep = "Temp")


DO_Experimentclean <- DO_Experiment %>%
  select("Day", "Mouse ID", "RBC (million/uL)") %>%
  subset(Day %in% c(0:15))

test2 <- spread(DO_Experimentclean, key = "Day", value ="RBC (million/uL)", sep = "RBC")

test3 <- merge(test,test2)

a <- 2:13
b <- 14:25
test4 <- test3[ , c(1,rbind(a,b))]

list(DayTemp = 2:13, DayRBC = 14:25)

c(1,rbind(a,b))[2:13]

names(test4)[1.5:12.5*2]

names(test3)[14]
cld3dtest <- cld3d(test4,timeInData=list(DayTemp = 1:12*2, DayRBC = 1.5:12.5*2))
kml3d(cld3dtest,3:5,nbRedrawing=20,toPlot="both")
### 3. Exporting results
try(choice(cld3dtest))
### 4. Visualizing in 3D
plotMeans3d(cld3dPregTemp,4)

library(readxl)
Temperature_and_Percent_Weightloss_Clusters <- read_excel("Documents/Temperature and Percent Weightloss Clusters.xlsx")
head(Temperature_and_Percent_Weightloss_Clusters)
Temperature_and_Percent_Weightloss_Clusters$Same <- ifelse(Temperature_and_Percent_Weightloss_Clusters$`Delta Temperature Clusters`==Temperature_and_Percent_Weightloss_Clusters$`Percent Weightloss Clusters`,1,0)

ggplot(Temperature_and_Percent_Weightloss_Clusters, aes(x = `Delta Temperature Clusters`, `Percent Weightloss Clusters`)) + geom_jitter(aes(color =as.factor(Same))) + theme_classic(base_size = 18) + theme(legend.position = 'none')

query_genes(10, peak_Mbp - 1, peak_Mbp + 1)

beep()
```

